# Конфигурация подключённых устройств
device_count = 5
active_devices = 3
device_ids = [101, 102, 103, 104, 105]  #идентификаторы
device_settings = {brightness = 75, volume = 50, modes = [100, 17.6]}